apiVersion: nodecore.fluidos.eu/v1alpha1
kind: Flavour
metadata:
  creationTimestamp: "2023-11-16T16:13:52Z"
  generation: 2
  name: fluidos.eu-k8s-fluidos-bba29928
  namespace: fluidos
  resourceVersion: "1534"
  uid: 5ce9f378-014e-4cb4-b173-5a3530d8f78d
spec:
  characteristics:
    architecture: arm64
    cpu: 7970838142n
    ephemeral-storage: "0"
    gpu: "0"
    memory: 7879752Ki
    persistent-storage: "0"
  optionalFields:
    workerID: fluidos-provider-worker
  owner:
    domain: fluidos.eu
    ip: 172.18.0.7:30001
    nodeID: 46ltws9per
  policy:
    aggregatable:
      maxCount: 0
      minCount: 0
    partitionable:
      cpuMin: "0"
      cpuStep: "1"
      memoryMin: "0"
      memoryStep: 100Mi
  price:
    amount: ""
    currency: ""
    period: ""
  providerID: 46ltws9per
  type: k8s-fluidos