---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-1-remote-navigation
  labels:
    app: robot-1-remote-navigation
    group: robot-1
    robotType: simulated
spec:
  replicas: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: robot-1-remote-navigation
      group: robot-1
      robotType: simulated
  template:
    metadata:
      labels:
        app: robot-1-remote-navigation
        group: robot-1
        robotType: simulated
    spec:
      {{- include "remote-affinity" . }}
      restartPolicy: Always
      volumes:
       {{- include "zenoh-session-volumes" . }}
      containers:
          {{- include "zenoh-bridge" .}}
        - name: world
          {{- include "zenoh-env" .}}
          {{- include "simulation-image" .}}
          {{- include "lifecycle" .}}
          resources:
            limits:
              cpu: 2800m
              memory: 4000Mi
          volumeMounts:
            {{- include "zenoh-session-volume-mount" . }}
          envFrom:
            {{- include "ros-common-env" . }}
            {{- include "robot-1-env" . }}
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Release.Revision }}-world-env
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Release.Revision }}-launcher-navigation-env
          {{- include "ros-probes" . }}
