---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robot-1-navigation
  labels:
    app: robot-1-navigation
    group: robot-1
    robotType: simulated
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: robot-1-navigation
      group: robot-1
      robotType: simulated
  template:
    metadata:
      labels:
        app: robot-1-navigation
        group: robot-1
        robotType: simulated
    spec:
      restartPolicy: Always
      {{- if eq .Values.ros.rmw "rmw_zenoh_cpp" }}
      volumes:
       {{- include "zenoh-session-volumes" . }}
       {{- end }}
      containers:
        - name: world
          {{- include "simulation-image" .}}
          {{- include "lifecycle" .}}
          resources:
            requests:
              cpu: 1200m
              memory: 200Mi
          {{- if eq .Values.ros.rmw "rmw_zenoh_cpp" }}
          volumeMounts:
            {{- include "zenoh-session-volume-mount" . }}
          {{- end }}
          envFrom:
            {{- include "ros-common-env" . }}
            {{- include "robot-1-env" . }}
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Release.Revision }}-world-env
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Release.Revision }}-launcher-navigation-env
          {{- include "ros-probes" . }}
