---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rviz
  labels:
    app: rviz
    group: robot-common-group
    robotType: simulated
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rviz
      group: robot-common-group
      robotType: simulated
  replicas: 1
  template:
    metadata:
      labels:
        app: rviz
        group: robot-common-group
        robotType: simulated
    spec:
      volumes:
        {{- include "web-volumes" . }}
        {{- include "zenoh-session-volumes" . }}
      initContainers:
        {{- include "novnc-container" . }}
      containers:
        - name: rviz
          {{- include "simulation-image" .}}
          {{- include "lifecycle" .}}
          volumeMounts:
            - name: data
              mountPath: /home/robot/data
            {{- include "zenoh-session-volume-mount" . }}
          envFrom:
            {{- include "ros-common-env" . }}
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Release.Revision }}-world-env
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Release.Revision }}-launcher-rviz-env
          ports:
            - containerPort: 5900
              name: vnc
          resources:
            requests:
              cpu: 1800m
              memory: 600Mi
        {{- include "websockify-container" . }}
        {{- include "webserver-container" . }}
        {{- include "php-container" . }}
          env:
            - name: WEBSOCKITY_PATH
              value: "websocket"
        {{- include "filebrowser-container" . }}