---
name: documentation

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      FILES_TO_COMMIT: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}/charts:/helm-docs
          image: jnorwood/helm-docs:v1.14.2
          run: /usr/bin/helm-docs --skip-version-footer
      - run: |
          git add .
          echo "FILES_TO_COMMIT=$(git diff --name-only --cached)" >> "$GITHUB_ENV"
      - name: Commit file
        uses: chromeq/commit@v2.x
        if: ${{ env.FILES_TO_COMMIT != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ env.FILES_TO_COMMIT }}
          commit-message: Automated chart README.md update
          ref: ${{ github.ref }}