---
name: documentation

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - uses: addnab/docker-run-action@v3
        with:
          options: -v ${{ github.workspace }}/charts:/helm-docs
          image: jnorwood/helm-docs:v1.14.2
          run: /usr/bin/helm-docs --skip-version-footer
      - run: |
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update Chart readme"
            git push
          else
            echo "No changes to commit."
          fi
      # # Commit all changed files back to the repository
      # - uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: Update Chart readme
