{{ if eq .Values.ros.rmw "rmw_zenoh_cpp" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.zenoh.name }}
spec:
  ports:
    - name: zenoh
      port: {{ .Values.services.zenoh.port }}
      targetPort: {{ .Values.services.zenoh.port }}
      protocol: {{ .Values.services.zenoh.proto  }}
  selector:
    app: zenoh-rmw-router
    group: robot-common-group
    robotType: simulated
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.gazebo.name }}
spec:
  type: ClusterIP
  ports:
    - name: gazebo
      port: {{ .Values.services.gazebo.port }}
      protocol: TCP
  selector:
    app: gazebo-server
    group: robot-common-group
    robotType: simulated
---
---
apiVersion: v1
kind: Service
metadata:
  name: rviz
spec:
  type: ClusterIP
  ports:
    - name: websocket
      port: 8080
      targetPort: 8080
    - name: webserver
      port: 80
      targetPort: 80
      protocol: TCP
    - name: fileserver
      port: 81
      targetPort: 81
      protocol: TCP
  selector:
    app: rviz
    group: robot-common-group
    robotType: simulated
